DATADIR ?= /usr/local/share/exorsim/

BIN = exor09

OBJS = utils.o exor.o sim6809.o asm6809.o unasm6809.o exorterm.o mon.o lpt.o drive.o

CFLAGS = -DM6809 -g -Wall -DDATADIR=\"$(DATADIR)\"

$(BIN) : $(OBJS)
	$(CC) $(CFLAGS) $(LDFLAGS) -o $(BIN) $(OBJS)

clean :
	rm -rf $(BIN) $(OBJS)
