DATADIR ?= /usr/local/share/exorsim/

BIN = exor

OBJS = utils.o exor.o sim6800.o asm6800.o unasm6800.o exorterm.o mon.o lpt.o drive.o

CFLAGS = -DM6800 -g -Wall -DDATADIR=\"$(DATADIR)\"

$(BIN) : $(OBJS)
	$(CC) $(CFLAGS) $(LDFLAGS) -o $(BIN) $(OBJS)

clean :
	rm -rf $(BIN) $(OBJS)
